#!/bin/bash
source /usr/lib/libtmplinux.sh
NAME=debian
init
DEBIAN_RELEASE="trixie"

issfs || {
    debootstrap --variant=minbase "$DEBIAN_RELEASE" "$TMP" http://deb.debian.org/debian
    passwd --root "$TMP" -d root
    chroot "$TMP" apt-get update
    chroot "$TMP" apt-get install -y "systemd-sysv"
    if [[ $# -gt 0 ]]; then
        chroot "$TMP" apt-get install -y "$@"
    fi
    mksquashfs "$TMP" "$SFS" -comp zstd
}

boot $1
